name: CI Creacion de EC2 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurando AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1

      - name: Crear EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id $MY_AMI \
            --count 1 \
            --instance-type t2.micro \
            --key-name $MY_KEY \
            --security-group-ids $MY_SG \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=Desafio-Rod-02}]'
